version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - './app:/app'
    ports:
      - 3001:3000
      - 19000:19000
      - 19006:19006
    environment:
      - CHOKIDAR_USEPOLLING=true